version: "3.0"
services:
  db:
    container_name: "NewDB"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5436:5432"

  web:
    build:
      context: .
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=_wCCQ6Zg4FGrn34Dm2_RPtlUf4wN5H5jB_1Uww--lcg=
    container_name: "NewAPP"
    ports:
      - 8010:8000
    depends_on:
      - db
      - migration

  migration:
    build:
      context: .
    restart: always
    command: alembic upgrade head
    depends_on:
      - db
