version: "3.0"
services:
  db:
    container_name: "NewDB"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: -p 5432
    expose:
      - 5432


  web:
    build:
      context: .
    command: sh -c "alembic upgrade head && uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    container_name: "NewAPP"
    ports:
      - 8010:8000
    depends_on:
      - db
volumes:
  postgres_data:

networks:
  custom:
    driver: bridge
