version: "3.0"
services:
  db:
    container_name: "db_app"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: -p 5433
    expose:
      - 5433

  web:
    build:
      context: .
    command: uvicorn --reload api.app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - 8010:8000
    depends_on:
      - db
volumes:
  postgres_data:

networks:
  custom:
    driver: bridge