"""Database Creation

Revision ID: 0a65e1135994
Revises: 
Create Date: 2023-10-21 15:19:03.766871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a65e1135994"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_create",
        sa.Column("text_uuid", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column(
            "death_token", sa.Boolean(create_constraint=True), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("text_uuid"),
        sa.UniqueConstraint("text_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("text_create")
    # ### end Alembic commands ###
