"""Add Tutorial model

Revision ID: 41d7980f2747
Revises: 84f0aad5918f
Create Date: 2023-09-24 19:11:07.110123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41d7980f2747'
down_revision: Union[str, None] = '84f0aad5918f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_create',
                    sa.Column('text_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('salt', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('text_id')
                    )
    op.create_index(op.f('ix_text_create_text_id'), 'text_create', ['text_id'], unique=False)
    op.drop_table('text_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_table',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='text_table_pkey')
                    )
    op.drop_index(op.f('ix_text_create_text_id'), table_name='text_create')
    op.drop_table('text_create')
    # ### end Alembic commands ###
