"""Add key_with_salt

Revision ID: 487747727134
Revises: 5645a20a30f7
Create Date: 2023-09-27 11:00:57.704902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487747727134'
down_revision: Union[str, None] = '5645a20a30f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_create', sa.Column('key_with_salt', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'text_create', ['id'])
    op.drop_column('text_create', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_create', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'text_create', type_='unique')
    op.drop_column('text_create', 'key_with_salt')
    # ### end Alembic commands ###
