"""delete datetime

Revision ID: 6acaab3ba4ed
Revises: 89cf71098ead
Create Date: 2023-09-27 12:06:13.233792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acaab3ba4ed'
down_revision: Union[str, None] = '89cf71098ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_create', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_create', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
