"""Database

Revision ID: a653e5cd5f7c
Revises: 
Create Date: 2023-09-22 21:31:03.482431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a653e5cd5f7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_table',
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('salt', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_table')
    # ### end Alembic commands ###
