"""Database creation

Revision ID: b19c56dabebb
Revises: 
Create Date: 2023-09-22 11:20:31.974025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b19c56dabebb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_table',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('salt', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_table')
    # ### end Alembic commands ###
